# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo
environment:

  matrix:
    - PYTHON: "C:\\Python36-conda64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

install:
  # Install miniconda Python
  - "powershell ./ci/install_python.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # install xarray and dependencies
  - "conda env create --file ./ci/requirements-py36-windows.yml"
  - "activate test_env"
  - "conda list"
  - "python setup.py install"

build: false

test_script:
  - "py.test cfanalytics --verbose"